package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.UploadInfo;
import greendao.DownloadInfo;

import greendao.UploadInfoDao;
import greendao.DownloadInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig uploadInfoDaoConfig;
    private final DaoConfig downloadInfoDaoConfig;

    private final UploadInfoDao uploadInfoDao;
    private final DownloadInfoDao downloadInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        uploadInfoDaoConfig = daoConfigMap.get(UploadInfoDao.class).clone();
        uploadInfoDaoConfig.initIdentityScope(type);

        downloadInfoDaoConfig = daoConfigMap.get(DownloadInfoDao.class).clone();
        downloadInfoDaoConfig.initIdentityScope(type);

        uploadInfoDao = new UploadInfoDao(uploadInfoDaoConfig, this);
        downloadInfoDao = new DownloadInfoDao(downloadInfoDaoConfig, this);

        registerDao(UploadInfo.class, uploadInfoDao);
        registerDao(DownloadInfo.class, downloadInfoDao);
    }
    
    public void clear() {
        uploadInfoDaoConfig.getIdentityScope().clear();
        downloadInfoDaoConfig.getIdentityScope().clear();
    }

    public UploadInfoDao getUploadInfoDao() {
        return uploadInfoDao;
    }

    public DownloadInfoDao getDownloadInfoDao() {
        return downloadInfoDao;
    }

}
