package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DOWNLOAD_INFO.
 */
public class DownloadInfo {

    private Long id;
    /** Not-null value. */
    private String user;
    /** Not-null value. */
    private String filename;
    /** Not-null value. */
    private String from;
    /** Not-null value. */
    private String to;
    /** Not-null value. */
    private java.util.Date uploadTime;
    private Integer percent;
    private Integer state;
    private Boolean autoSyncDownload;
    private Long totalSize;
    private Integer hashCode;

    public DownloadInfo() {
    }

    public DownloadInfo(Long id) {
        this.id = id;
    }

    public DownloadInfo(Long id, String user, String filename, String from, String to, java.util.Date uploadTime, Integer percent, Integer state, Boolean autoSyncDownload, Long totalSize, Integer hashCode) {
        this.id = id;
        this.user = user;
        this.filename = filename;
        this.from = from;
        this.to = to;
        this.uploadTime = uploadTime;
        this.percent = percent;
        this.state = state;
        this.autoSyncDownload = autoSyncDownload;
        this.totalSize = totalSize;
        this.hashCode = hashCode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUser() {
        return user;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser(String user) {
        this.user = user;
    }

    /** Not-null value. */
    public String getFilename() {
        return filename;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /** Not-null value. */
    public String getFrom() {
        return from;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFrom(String from) {
        this.from = from;
    }

    /** Not-null value. */
    public String getTo() {
        return to;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTo(String to) {
        this.to = to;
    }

    /** Not-null value. */
    public java.util.Date getUploadTime() {
        return uploadTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUploadTime(java.util.Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    public Integer getPercent() {
        return percent;
    }

    public void setPercent(Integer percent) {
        this.percent = percent;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Boolean getAutoSyncDownload() {
        return autoSyncDownload;
    }

    public void setAutoSyncDownload(Boolean autoSyncDownload) {
        this.autoSyncDownload = autoSyncDownload;
    }

    public Long getTotalSize() {
        return totalSize;
    }

    public void setTotalSize(Long totalSize) {
        this.totalSize = totalSize;
    }

    public Integer getHashCode() {
        return hashCode;
    }

    public void setHashCode(Integer hashCode) {
        this.hashCode = hashCode;
    }

}
